 # GET   http://localhost:4000/users/

# POST http://localhost:4000/?abc=abc
# Content-Type: application/json

# {
#     "bien" : "gia_tri"
# }

 GET http://localhost:4000/user/machchitai@gmail.com

# POST http://localhost:4000/user/
# Content-Type: application/json
# Authorization: Basic dXNlcm5hbWU6cGFzc3dvcmQ=

# {
#     "name": "name",
#     "username":"username",  
#     "password": "password",
#     "email": "email",
#     "phone":"phone"
# }