# GET   http://localhost:4000/movies?thoi_luong=120
# Content-Type: application/json

GET   http://localhost:4000/message
Content-Type: application/json

# POST http://localhost:4000/?abc=abc
# Content-Type: application/json

# {
#     "bien" : "gia_tri"
# }

# GET http://localhost:4000/user/machchitai


# POST http://localhost:4000/users
# Content-Type: application/json
# Authorization: Basic bWFjaGNoaXRhaToxMjMxMjM=

# [
#     {
#         "name":"Tai Mach",  
#         "username":"machchitai",
#         "password":"123123",
#         "email":"machchitai@gmail.com"
#     },
#     {
#         "name":"Tai Mach 2",
#         "username":"machchitai",
#         "password":"123123",
#         "email":"machchitai2@gmail.com"
#     },
#     {
#         "name":"Tai Mach 3",
#         "username":"machchitai",
#         "password":"123123",
#         "email":"machchitai3@gmail.com"
#     }

# ]


# POST http://localhost:4000/user/sign-up
# Content-Type: application/json

# {
#     "name":"Tai Mach",
#     "username":"machchitai",
#     "password":"123123",
#     "email":"machchitai2@gmail.com"
# }

# PUT http://localhost:4000/user/machchitai1994@gmail.com
# Content-Type: application/json

# {
#     "name":"Tai Mach",
#     "username":"machchitai",
#     "password":"123123",
#     "email":"machchitai@gmail.com"
# }

# DELETE http://localhost:4000/user/machchitai2@gmail.com
# Content-Type: application/json
# Authorization: Basic bWFjaGNoaXRhaToxMjMxMjM=

# POST http://localhost:4000/user/log-in
# Content-Type: application/json

# {
#     "tai_khoan": "machchitai",
#     "mat_khau": "123123"
# }